### ISSUE TITLE
Container won't start

### ISSUE THREAD

**Issue by markusstam** [evbauer/MESA-Docker#16]
I have never used Docker before, but I recently installed it (along with the requisite Linux kernel, and XMing) in order to use MESA on the Windows 10 Home operating system. I cloned the git files correctly, but every time I attempt to start the container in the git bash terminal, I eventually get 
`Error checking TLS connection: Error checking and/or regenerating the certs` , then, after a couple lines, `Error: No such container: mesa_dock`, then an invitation to enter the first password. Once I correctly enter it, I get
`Connection closed by 192.168.99.100 port 22`
`password is mesa`
`ssh: connect to host localhost port 20000: Connection refused` 
`Error response from daemon: Cannot kill container: mesa_dock: No such container: mesa_dock` 
`Stopping "mesa-machine"...` 
I've checked, and Docker seems to be running okay outside of this, so I'm wondering what's wrong. It seems like there's a server-side error, but it is also possible I installed something improperly; I make no illusion of being very knowledgeable about any of this, and any feedback (including that this is the wrong area to post this concern), no matter how basic, would be much appreciated.

**Comment by evbauer** [comment]
This is definitely the right place! I'll do my best to help, though I have to admit it can be challenging to support Windows 10 Home these days since I no longer have a computer with that operation system easily at hand.

Can you confirm a couple of things just so I can make sure I understand your setup?
* Your computer is running on Windows 10 Home
* You installed Docker Toolbox from here: https://github.com/docker/toolbox/releases
* You're attempting to launch via the `win_home_dockerMESA.sh` script

Is that all correct? If so, would you mind pasting the entire output here so I can try to read it and understand what might be going on?

**Comment by markusstam** [comment]
Of the bullet points, it is not true that I have installed Docker Toolbox--it is deprecated and urges use of Docker Desktop instead. While it is possible that was part of the issue, I attempted installing the older software (I say "attempted", because one step of the installation instructions said to use a "make" command that bash didn't recognize), and ended up with the same output (again, maybe this would be different if I was able to properly construct Docker Toolbox, but the link to the documentation leads to a page about transferring files to Docker Desktop now):
<img width="469" alt="Capture" src="https://user-images.githubusercontent.com/80275823/114103883-82f87b80-988f-11eb-968b-6d1357ec2a3d.PNG">
It doesn't show the password when I type it in, but rest assured it will only continue to run if "tcuser" is entered correctly.
Using the terminal from Docker Toolbox (which, again, may not be properly constructed) gives the same result as git bash.

**Comment by evbauer** [comment]
Thanks! That makes a big difference. I designed all of this when Docker Toolbox was still the standard way of using Docker on Windows 10 Home, but it seems that things have evolved since then. If you can't get Docker Toolbox installed, it makes sense that the `win_home_dockerMESA.sh` script does not work.

What happens if you use the other script for windows `win_dockerMESA.sh`?

If that doesn't work, it sounds like your best bet will probably be to try using WSL2 rather than Docker. You can find some instructions for that here: https://docs.mesastar.org/en/latest/windows-install.html#option-2-wsl2

**Comment by markusstam** [comment]
I ended up just installing Ubuntu to do it. For some reason, the system refuses to acknowledge that the gz file I downloaded from the SDK site exists on my computer (I even renamed it simply "mesa" to ensure I wasn't entering the name in wrong), but that's something I should hopefully be able to figure out myself. Thank you for your time and attention, though!

**Comment by evbauer** [comment]
Ok, sounds good. Ubuntu is a great operating system, so that should be a great solution for you. Good luck!
